# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_auto_20170331_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to='dream.User'),
        ),
    ]
